# Generated by Django 6.1 on 2026-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tinaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('ubicacion', models.CharField(max_length=120)),
                ('capacidad_litros', models.IntegerField(default=1100)),
                ('ph_actual', models.FloatField(default=7.0)),
                ('fecha_medicion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
