# Generated by Django 6.1 on 2026-09-16 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id_medicion', models.DateTimeField(db_column='Id_medicion', default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('ph_medicion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('agua_medicion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_medicion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'medicion',
                'ordering': ['-fecha_medicion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='Id_rol', primary_key=True, serialize=False)),
                ('rol', models.CharField(db_column='Rol', max_length=30)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tinaco',
            fields=[
                ('id_tinaco', models.DateTimeField(db_column='Id_Tinaco', default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('nombre_tinaco', models.CharField(blank=True, max_length=15, null=True)),
                ('capacidad_tinaco', models.IntegerField()),
            ],
            options={
                'db_table': 'tinaco',
                'ordering': ['id_tinaco'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.DateTimeField(db_column='Id_ubicacion', default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('region', models.CharField(db_column='Region', max_length=42)),
                ('ciudad', models.CharField(db_column='Ciudad', max_length=20)),
                ('comuna', models.CharField(db_column='Comuna', max_length=20)),
                ('calle', models.CharField(db_column='Calle', max_length=50)),
                ('numero', models.IntegerField(db_column='Numero')),
            ],
            options={
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.DateTimeField(db_column='Id_usuario', default=django.utils.timezone.now, primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=20)),
                ('email_usuario', models.CharField(max_length=30, unique=True)),
                ('password_usuario', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
